#!/bin/bash

docker-compose down

docker-compose up -d --force-recreate

docker run --rm -v $(pwd):/app composer install

docker-compose exec app php artisan config:cache

docker-compose exec app php artisan migrate

docker run -v $(pwd):/app --rm nielsvdoorn/laravel-phpunit:latest ./vendor/bin/phpunit --configuration phpunit.xml tests

>&2 echo "Your application back end is now ready to serve APIs"